version: '3'

services:
  bot:
    image: brainexe/slack-bot:latest
    restart: always
    volumes:
      - ./config.yaml:/config/config.yaml:ro
      - ./bot.log:/bot.log
      - bot-data:/storage
    command: ./app -config /config/*.yaml

volumes:
  bot-data: